-- =========================================================
-- MÓDULO 10 · CLASIFICACIÓN NETA (PostgreSQL / Supabase)
-- Objetivo: versionar clasificación, registrar variación y auditar cambios
-- Compatible con esquema actual (cambios progresivos)
-- =========================================================

BEGIN;

-- 1) CABECERA DEL PROCESO DE CLASIFICACIÓN NETA POR LOTE
CREATE TABLE IF NOT EXISTS clasificacion_neta_proceso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lote_id BIGINT NOT NULL REFERENCES lotes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  version_actual INT NOT NULL DEFAULT 1,
  total_modificaciones INT NOT NULL DEFAULT 0,
  estado VARCHAR(20) NOT NULL DEFAULT 'abierto' CHECK (estado IN ('abierto','cerrado','anulado')),

  peso_bruto_ingreso NUMERIC(12,3) NOT NULL DEFAULT 0,
  peso_bruto_clasificado NUMERIC(12,3) NOT NULL DEFAULT 0,
  peso_neto_clasificado NUMERIC(12,3) NOT NULL DEFAULT 0,

  numero_jabas_ingreso INT NOT NULL DEFAULT 0,
  numero_jabas_clasificacion INT NOT NULL DEFAULT 0,

  variacion_kg NUMERIC(12,3) NOT NULL DEFAULT 0,
  variacion_pct NUMERIC(8,4) NOT NULL DEFAULT 0,

  observaciones TEXT,
  created_by_persona_id BIGINT REFERENCES personas(id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_by_persona_id BIGINT REFERENCES personas(id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

  CONSTRAINT uk_clasificacion_neta_lote UNIQUE (lote_id)
);

CREATE INDEX IF NOT EXISTS idx_clasificacion_neta_estado
  ON clasificacion_neta_proceso (estado);

CREATE INDEX IF NOT EXISTS idx_clasificacion_neta_updated
  ON clasificacion_neta_proceso (updated_at DESC);

-- 2) AJUSTES A DETALLE EXISTENTE PARA VERSIONAMIENTO
ALTER TABLE lote_clasificacion
  ADD COLUMN IF NOT EXISTS clasificacion_proceso_id BIGINT REFERENCES clasificacion_neta_proceso(id) ON UPDATE CASCADE ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS version_no INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS es_vigente BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS created_by_persona_id BIGINT REFERENCES personas(id) ON UPDATE CASCADE ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS updated_by_persona_id BIGINT REFERENCES personas(id) ON UPDATE CASCADE ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();

-- Convertir unicidad anterior a unicidad parcial por fila vigente
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'uk_lote_categoria'
      AND conrelid = 'lote_clasificacion'::regclass
  ) THEN
    ALTER TABLE lote_clasificacion DROP CONSTRAINT uk_lote_categoria;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_lote_categoria_vigente
  ON lote_clasificacion (lote_id, categoria_id)
  WHERE es_vigente = TRUE;

CREATE INDEX IF NOT EXISTS idx_lote_clasificacion_version
  ON lote_clasificacion (lote_id, version_no DESC);

CREATE INDEX IF NOT EXISTS idx_lote_clasificacion_vigente
  ON lote_clasificacion (lote_id, es_vigente);

-- 3) BITÁCORA DE CAMBIOS DE CLASIFICACIÓN
CREATE TABLE IF NOT EXISTS lote_clasificacion_auditoria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lote_id BIGINT NOT NULL REFERENCES lotes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  clasificacion_proceso_id BIGINT REFERENCES clasificacion_neta_proceso(id) ON UPDATE CASCADE ON DELETE SET NULL,
  lote_clasificacion_id BIGINT REFERENCES lote_clasificacion(id) ON UPDATE CASCADE ON DELETE SET NULL,

  accion VARCHAR(20) NOT NULL CHECK (accion IN ('crear','editar','anular','cerrar')),
  version_anterior INT,
  version_nueva INT,

  peso_neto_anterior NUMERIC(12,3),
  peso_neto_nuevo NUMERIC(12,3),
  diferencia_kg NUMERIC(12,3),

  motivo TEXT NOT NULL,
  actor_persona_id BIGINT REFERENCES personas(id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_clasif_auditoria_lote
  ON lote_clasificacion_auditoria (lote_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_clasif_auditoria_actor
  ON lote_clasificacion_auditoria (actor_persona_id, created_at DESC);

-- 4) REGISTRO DE VARIACIONES DE PESO DEL LOTE
CREATE TABLE IF NOT EXISTS lote_variacion_peso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lote_id BIGINT NOT NULL REFERENCES lotes(id) ON UPDATE CASCADE ON DELETE CASCADE,
  clasificacion_proceso_id BIGINT REFERENCES clasificacion_neta_proceso(id) ON UPDATE CASCADE ON DELETE SET NULL,

  peso_ingreso NUMERIC(12,3) NOT NULL,
  peso_neto_clasificado NUMERIC(12,3) NOT NULL,
  variacion_kg NUMERIC(12,3) NOT NULL,
  variacion_pct NUMERIC(8,4) NOT NULL,

  tipo_variacion VARCHAR(20) NOT NULL CHECK (tipo_variacion IN ('merma','ganancia','sin_cambio')),
  causa_variacion VARCHAR(30) NOT NULL CHECK (causa_variacion IN ('humedad','tierra','negociacion','proceso','otro')),
  detalle_causa TEXT,

  actor_persona_id BIGINT REFERENCES personas(id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lote_variacion_lote
  ON lote_variacion_peso (lote_id, created_at DESC);

-- 5) TRIGGER: actualizar updated_at en tablas de proceso y detalle
CREATE OR REPLACE FUNCTION trg_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS t_touch_clasificacion_neta_proceso ON clasificacion_neta_proceso;
CREATE TRIGGER t_touch_clasificacion_neta_proceso
BEFORE UPDATE ON clasificacion_neta_proceso
FOR EACH ROW
EXECUTE FUNCTION trg_touch_updated_at();

DROP TRIGGER IF EXISTS t_touch_lote_clasificacion ON lote_clasificacion;
CREATE TRIGGER t_touch_lote_clasificacion
BEFORE UPDATE ON lote_clasificacion
FOR EACH ROW
EXECUTE FUNCTION trg_touch_updated_at();

-- 6) VISTA DE CLASIFICACIÓN VIGENTE (fuente limpia para liquidación cliente y reportes)
CREATE OR REPLACE VIEW vw_lote_clasificacion_vigente AS
SELECT
  lc.id,
  lc.lote_id,
  lc.categoria_id,
  lc.codigo_clasificacion,
  lc.peso_bruto,
  lc.numero_jabas,
  lc.peso_jabas,
  lc.porcentaje_humedad,
  lc.peso_descuento_humedad,
  lc.peso_neto,
  lc.fecha_clasificacion,
  lc.version_no,
  lc.clasificacion_proceso_id,
  l.numero_lote,
  l.productor_id,
  l.fecha_ingreso,
  c.codigo AS categoria_codigo,
  c.nombre AS categoria_nombre
FROM lote_clasificacion lc
JOIN lotes l ON l.id = lc.lote_id
JOIN categorias c ON c.id = lc.categoria_id
WHERE lc.es_vigente = TRUE;

-- 7) BACKFILL INICIAL (NO DESTRUCTIVO)
-- Crea un proceso por cada lote que ya tiene clasificación y no tiene proceso creado.
INSERT INTO clasificacion_neta_proceso (
  lote_id,
  version_actual,
  total_modificaciones,
  estado,
  peso_bruto_ingreso,
  peso_bruto_clasificado,
  peso_neto_clasificado,
  numero_jabas_ingreso,
  numero_jabas_clasificacion,
  variacion_kg,
  variacion_pct,
  observaciones,
  created_at,
  updated_at
)
SELECT
  l.id AS lote_id,
  1 AS version_actual,
  0 AS total_modificaciones,
  'cerrado' AS estado,
  COALESCE(l.peso_bruto_ingreso, 0) AS peso_bruto_ingreso,
  COALESCE(SUM(lc.peso_bruto), 0) AS peso_bruto_clasificado,
  COALESCE(SUM(lc.peso_neto), 0) AS peso_neto_clasificado,
  COALESCE(l.numero_jabas, 0) AS numero_jabas_ingreso,
  COALESCE(SUM(lc.numero_jabas), 0)::INT AS numero_jabas_clasificacion,
  COALESCE(SUM(lc.peso_neto), 0) - COALESCE(l.peso_bruto_ingreso, 0) AS variacion_kg,
  CASE
    WHEN COALESCE(l.peso_bruto_ingreso, 0) > 0
      THEN ((COALESCE(SUM(lc.peso_neto), 0) - COALESCE(l.peso_bruto_ingreso, 0)) / l.peso_bruto_ingreso) * 100
    ELSE 0
  END AS variacion_pct,
  'Backfill inicial módulo 10' AS observaciones,
  NOW(),
  NOW()
FROM lotes l
JOIN lote_clasificacion lc ON lc.lote_id = l.id
LEFT JOIN clasificacion_neta_proceso cnp ON cnp.lote_id = l.id
WHERE cnp.id IS NULL
GROUP BY l.id, l.peso_bruto_ingreso, l.numero_jabas;

-- Enlaza detalle histórico al proceso creado (solo si no estaba enlazado)
UPDATE lote_clasificacion lc
SET clasificacion_proceso_id = cnp.id
FROM clasificacion_neta_proceso cnp
WHERE cnp.lote_id = lc.lote_id
  AND lc.clasificacion_proceso_id IS NULL;

COMMIT;
