CREATE TABLE IF NOT EXISTS pedido_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  categoria_id BIGINT NOT NULL,
  kg_solicitados NUMERIC(10,2) NOT NULL,
  precio_kg NUMERIC(10,2) NOT NULL,
  kg_asignados NUMERIC(10,2) NOT NULL DEFAULT 0,
  prioridad INT NOT NULL DEFAULT 1,
  permite_sustitucion BOOLEAN NOT NULL DEFAULT FALSE,
  requiere_revision BOOLEAN NOT NULL DEFAULT FALSE,
  observaciones TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_ped_det_pedido FOREIGN KEY (pedido_id)
    REFERENCES pedidos(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_ped_det_categoria FOREIGN KEY (categoria_id)
    REFERENCES categorias(id) ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ped_det_pedido ON pedido_detalle (pedido_id);
CREATE INDEX IF NOT EXISTS idx_ped_det_categoria ON pedido_detalle (categoria_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ped_det_pedido_categoria
  ON pedido_detalle (pedido_id, categoria_id);

ALTER TABLE pedido_asignaciones
  ADD COLUMN IF NOT EXISTS pedido_detalle_id BIGINT,
  ADD COLUMN IF NOT EXISTS sin_clasificacion_neta BOOLEAN NOT NULL DEFAULT FALSE;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'fk_ped_asig_detalle'
      AND table_name = 'pedido_asignaciones'
  ) THEN
    ALTER TABLE pedido_asignaciones
      ADD CONSTRAINT fk_ped_asig_detalle
      FOREIGN KEY (pedido_detalle_id)
      REFERENCES pedido_detalle(id)
      ON UPDATE CASCADE
      ON DELETE SET NULL;
  END IF;
END $$;

INSERT INTO pedido_detalle (
  pedido_id,
  categoria_id,
  kg_solicitados,
  precio_kg,
  kg_asignados,
  prioridad,
  permite_sustitucion,
  requiere_revision,
  observaciones
)
SELECT
  p.id,
  p.categoria_id,
  COALESCE(p.kg_solicitados, 0),
  COALESCE(p.precio_kg, 0),
  0,
  1,
  FALSE,
  FALSE,
  NULL
FROM pedidos p
WHERE p.categoria_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM pedido_detalle pd
    WHERE pd.pedido_id = p.id
      AND pd.categoria_id = p.categoria_id
  );

UPDATE pedido_asignaciones pa
SET pedido_detalle_id = pd.id
FROM pedido_detalle pd
WHERE pd.pedido_id = pa.pedido_id
  AND pd.categoria_id = pa.categoria_id
  AND pa.pedido_detalle_id IS NULL;
