BEGIN;

-- =============================================================
-- MIGRACION UNICA CONSOLIDADA (MOD 2 + MOD 5 + MOD 6)
-- Este script reemplaza la necesidad de correr scripts sueltos previos.
-- Es idempotente: se puede ejecutar sin romper si ya fue aplicado.
-- =============================================================

-- 1) Lotes: categoria opcional + producto controlado
ALTER TABLE lotes
ADD COLUMN IF NOT EXISTS categoria_id BIGINT;

UPDATE lotes
SET producto = CASE
  WHEN lower(trim(producto)) IN ('curcuma', 'cúrcuma') THEN 'Curcuma'
  ELSE 'Jengibre'
END
WHERE producto IS NULL
   OR lower(trim(producto)) NOT IN ('jengibre', 'curcuma', 'cúrcuma');

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'ck_lotes_producto_permitido'
  ) THEN
    ALTER TABLE lotes
    ADD CONSTRAINT ck_lotes_producto_permitido
    CHECK (producto IN ('Jengibre','Curcuma'));
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_lotes_categoria'
  ) THEN
    ALTER TABLE lotes
    ADD CONSTRAINT fk_lotes_categoria
    FOREIGN KEY (categoria_id)
    REFERENCES categorias(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL;
  END IF;
END$$;

CREATE INDEX IF NOT EXISTS idx_lotes_categoria ON lotes (categoria_id);

-- 2) Pedidos: alinear producto permitido con la app
UPDATE pedidos
SET producto = CASE
  WHEN lower(trim(producto)) IN ('curcuma', 'cúrcuma') THEN 'Curcuma'
  ELSE 'Jengibre'
END
WHERE producto IS NULL
   OR lower(trim(producto)) NOT IN ('jengibre', 'curcuma', 'cúrcuma');

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'ck_pedidos_producto_permitido'
  ) THEN
    ALTER TABLE pedidos
    ADD CONSTRAINT ck_pedidos_producto_permitido
    CHECK (producto IN ('Jengibre','Curcuma'));
  END IF;
END$$;

-- 3) Liquidaciones: comprobante de pago irrepetible (mod 5 y 6)
UPDATE liquidaciones
SET numero_comprobante = NULL
WHERE numero_comprobante IS NOT NULL
  AND btrim(numero_comprobante) = '';

CREATE UNIQUE INDEX IF NOT EXISTS uq_liq_numero_comprobante
  ON liquidaciones (numero_comprobante)
  WHERE numero_comprobante IS NOT NULL;

-- Si quedó un índice duplicado por script previo alterno, lo removemos.
DROP INDEX IF EXISTS uk_liquidaciones_numero_comprobante;

-- 4) Adelantos: comprobante único para soporte de copia empresa-productor
ALTER TABLE adelantos
ADD COLUMN IF NOT EXISTS numero_comprobante VARCHAR(30);

UPDATE adelantos
SET numero_comprobante = NULL
WHERE numero_comprobante IS NOT NULL
  AND btrim(numero_comprobante) = '';

CREATE UNIQUE INDEX IF NOT EXISTS uq_adelantos_numero_comprobante
  ON adelantos (numero_comprobante)
  WHERE numero_comprobante IS NOT NULL;

-- 5) Comprobantes internos de control (adelanto / venta / liquidacion)
CREATE TABLE IF NOT EXISTS comprobantes_internos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('adelanto','venta','liquidacion')),
  codigo_interno VARCHAR(40) NOT NULL,
  entidad_origen VARCHAR(20) NOT NULL CHECK (entidad_origen IN ('adelantos','liquidaciones')),
  entidad_origen_id BIGINT NOT NULL,
  persona_principal_id BIGINT NOT NULL,
  productor_id BIGINT,
  cliente_id BIGINT,
  receptor_nombre VARCHAR(255),
  receptor_documento VARCHAR(30),
  receptor_rol VARCHAR(80),
  lugar_recepcion TEXT,
  gps_lat NUMERIC(10,7),
  gps_lng NUMERIC(10,7),
  gps_precision_m NUMERIC(10,2),
  fecha_evento DATE NOT NULL,
  hora_evento TIME,
  monto NUMERIC(12,2) NOT NULL DEFAULT 0,
  observaciones TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_comp_int_persona_principal FOREIGN KEY (persona_principal_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_comp_int_productor FOREIGN KEY (productor_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_comp_int_cliente FOREIGN KEY (cliente_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT uk_comp_int_codigo UNIQUE (codigo_interno),
  CONSTRAINT uk_comp_int_origen_tipo UNIQUE (entidad_origen, entidad_origen_id, tipo)
);

CREATE INDEX IF NOT EXISTS idx_comp_int_tipo ON comprobantes_internos (tipo);
CREATE INDEX IF NOT EXISTS idx_comp_int_fecha ON comprobantes_internos (fecha_evento);
CREATE INDEX IF NOT EXISTS idx_comp_int_productor ON comprobantes_internos (productor_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_cliente ON comprobantes_internos (cliente_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_persona_principal ON comprobantes_internos (persona_principal_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_payload_gin ON comprobantes_internos USING GIN (payload);

COMMIT;
