BEGIN;

CREATE TABLE IF NOT EXISTS comprobantes_internos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('adelanto','venta','liquidacion')),
  codigo_interno VARCHAR(40) NOT NULL,
  entidad_origen VARCHAR(20) NOT NULL CHECK (entidad_origen IN ('adelantos','liquidaciones')),
  entidad_origen_id BIGINT NOT NULL,
  persona_principal_id BIGINT NOT NULL,
  productor_id BIGINT,
  cliente_id BIGINT,
  receptor_nombre VARCHAR(255),
  receptor_documento VARCHAR(30),
  receptor_rol VARCHAR(80),
  lugar_recepcion TEXT,
  gps_lat NUMERIC(10,7),
  gps_lng NUMERIC(10,7),
  gps_precision_m NUMERIC(10,2),
  fecha_evento DATE NOT NULL,
  hora_evento TIME,
  monto NUMERIC(12,2) NOT NULL DEFAULT 0,
  observaciones TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_comp_int_persona_principal FOREIGN KEY (persona_principal_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_comp_int_productor FOREIGN KEY (productor_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_comp_int_cliente FOREIGN KEY (cliente_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT uk_comp_int_codigo UNIQUE (codigo_interno),
  CONSTRAINT uk_comp_int_origen_tipo UNIQUE (entidad_origen, entidad_origen_id, tipo)
);

CREATE INDEX IF NOT EXISTS idx_comp_int_tipo ON comprobantes_internos (tipo);
CREATE INDEX IF NOT EXISTS idx_comp_int_fecha ON comprobantes_internos (fecha_evento);
CREATE INDEX IF NOT EXISTS idx_comp_int_productor ON comprobantes_internos (productor_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_cliente ON comprobantes_internos (cliente_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_persona_principal ON comprobantes_internos (persona_principal_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_payload_gin ON comprobantes_internos USING GIN (payload);

COMMIT;
