-- Backfill de comprobantes internos para datos históricos
-- Ejecutar una sola vez después de crear la tabla comprobantes_internos

BEGIN;

-- Seguridad: crea tabla/índices si aún no existen
CREATE TABLE IF NOT EXISTS comprobantes_internos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('adelanto','venta','liquidacion')),
  codigo_interno VARCHAR(40) NOT NULL,
  entidad_origen VARCHAR(20) NOT NULL CHECK (entidad_origen IN ('adelantos','liquidaciones')),
  entidad_origen_id BIGINT NOT NULL,
  persona_principal_id BIGINT NOT NULL,
  productor_id BIGINT,
  cliente_id BIGINT,
  receptor_nombre VARCHAR(255),
  receptor_documento VARCHAR(30),
  receptor_rol VARCHAR(80),
  lugar_recepcion TEXT,
  gps_lat NUMERIC(10,7),
  gps_lng NUMERIC(10,7),
  gps_precision_m NUMERIC(10,2),
  fecha_evento DATE NOT NULL,
  hora_evento TIME,
  monto NUMERIC(12,2) NOT NULL DEFAULT 0,
  observaciones TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_comp_int_persona_principal FOREIGN KEY (persona_principal_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_comp_int_productor FOREIGN KEY (productor_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_comp_int_cliente FOREIGN KEY (cliente_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT uk_comp_int_codigo UNIQUE (codigo_interno),
  CONSTRAINT uk_comp_int_origen_tipo UNIQUE (entidad_origen, entidad_origen_id, tipo)
);

CREATE INDEX IF NOT EXISTS idx_comp_int_tipo ON comprobantes_internos (tipo);
CREATE INDEX IF NOT EXISTS idx_comp_int_fecha ON comprobantes_internos (fecha_evento);
CREATE INDEX IF NOT EXISTS idx_comp_int_productor ON comprobantes_internos (productor_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_cliente ON comprobantes_internos (cliente_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_persona_principal ON comprobantes_internos (persona_principal_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_payload_gin ON comprobantes_internos USING GIN (payload);

-- 1) Adelantos históricos sin comprobante interno
insert into comprobantes_internos (
  tipo,
  codigo_interno,
  entidad_origen,
  entidad_origen_id,
  persona_principal_id,
  productor_id,
  cliente_id,
  fecha_evento,
  hora_evento,
  monto,
  observaciones,
  payload
)
select
  'adelanto',
  concat('CI-ADI-HIST-', lpad(a.id::text, 10, '0')),
  'adelantos',
  a.id,
  a.productor_id,
  a.productor_id,
  null,
  a.fecha,
  null,
  a.monto,
  a.motivo,
  jsonb_build_object(
    'numero_comprobante_adelanto', a.numero_comprobante,
    'lote_id', a.lote_id,
    'backfill', true
  )
from adelantos a
where not exists (
  select 1
  from comprobantes_internos ci
  where ci.entidad_origen = 'adelantos'
    and ci.entidad_origen_id = a.id
    and ci.tipo = 'adelanto'
);

-- 2) Liquidaciones de productor históricas sin comprobante interno
insert into comprobantes_internos (
  tipo,
  codigo_interno,
  entidad_origen,
  entidad_origen_id,
  persona_principal_id,
  productor_id,
  cliente_id,
  fecha_evento,
  hora_evento,
  monto,
  observaciones,
  payload
)
select
  'liquidacion',
  concat('CI-LIQ-HIST-', lpad(l.id::text, 10, '0')),
  'liquidaciones',
  l.id,
  l.persona_id,
  l.persona_id,
  null,
  l.fecha_liquidacion,
  null,
  coalesce(l.total_a_pagar, l.total_bruto, 0),
  l.observaciones,
  jsonb_build_object(
    'numero_liquidacion', l.numero_liquidacion,
    'numero_comprobante', l.numero_comprobante,
    'lote_id', l.lote_id,
    'tipo_liquidacion', 'productor',
    'backfill', true
  )
from liquidaciones l
where l.tipo = 'productor'
  and l.estado <> 'anulada'
  and not exists (
    select 1
    from comprobantes_internos ci
    where ci.entidad_origen = 'liquidaciones'
      and ci.entidad_origen_id = l.id
      and ci.tipo = 'liquidacion'
  );

-- 3) Liquidaciones de cliente históricas sin comprobante interno (venta)
insert into comprobantes_internos (
  tipo,
  codigo_interno,
  entidad_origen,
  entidad_origen_id,
  persona_principal_id,
  productor_id,
  cliente_id,
  fecha_evento,
  hora_evento,
  monto,
  observaciones,
  payload
)
select
  'venta',
  concat('CI-VEN-HIST-', lpad(l.id::text, 10, '0')),
  'liquidaciones',
  l.id,
  l.persona_id,
  null,
  l.persona_id,
  l.fecha_liquidacion,
  null,
  coalesce(l.total_a_pagar, l.total_bruto, 0),
  l.observaciones,
  jsonb_build_object(
    'numero_liquidacion', l.numero_liquidacion,
    'numero_comprobante', l.numero_comprobante,
    'pedido_id', l.pedido_id,
    'tipo_liquidacion', 'cliente',
    'backfill', true
  )
from liquidaciones l
where l.tipo = 'cliente'
  and l.estado <> 'anulada'
  and not exists (
    select 1
    from comprobantes_internos ci
    where ci.entidad_origen = 'liquidaciones'
      and ci.entidad_origen_id = l.id
      and ci.tipo = 'venta'
  );

COMMIT;
