BEGIN;

CREATE TABLE IF NOT EXISTS personas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_completo VARCHAR(255) NOT NULL,
  tipo_documento VARCHAR(10) NOT NULL DEFAULT 'DNI' CHECK (tipo_documento IN ('DNI','RUC','CE')),
  documento VARCHAR(20) NOT NULL,
  telefono VARCHAR(20),
  email VARCHAR(255),
  direccion TEXT,
  banco VARCHAR(100),
  cuenta_bancaria VARCHAR(50),
  cci VARCHAR(30),
  estado VARCHAR(10) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo','inactivo')),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_personas_documento UNIQUE (tipo_documento, documento)
);

CREATE INDEX IF NOT EXISTS idx_personas_estado ON personas (estado);

CREATE TABLE IF NOT EXISTS persona_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_id BIGINT NOT NULL,
  rol VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_persona_roles_persona FOREIGN KEY (persona_id)
    REFERENCES personas(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uk_persona_rol UNIQUE (persona_id, rol)
);

DO $$
DECLARE
  r RECORD;
BEGIN
  IF to_regclass('public.persona_roles') IS NOT NULL THEN
    FOR r IN
      SELECT c.conname
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
      JOIN pg_namespace n ON n.oid = t.relnamespace
      WHERE c.contype = 'c'
        AND n.nspname = 'public'
        AND t.relname = 'persona_roles'
        AND pg_get_constraintdef(c.oid) ILIKE '%rol%'
    LOOP
      EXECUTE format('ALTER TABLE public.persona_roles DROP CONSTRAINT IF EXISTS %I', r.conname);
    END LOOP;

    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
      JOIN pg_namespace n ON n.oid = t.relnamespace
      WHERE c.contype = 'c'
        AND n.nspname = 'public'
        AND t.relname = 'persona_roles'
        AND c.conname = 'chk_persona_roles_rol'
    ) THEN
      ALTER TABLE public.persona_roles
        ADD CONSTRAINT chk_persona_roles_rol
        CHECK (rol IN (
          'productor',
          'cliente',
          'estibador',
          'transportista',
          'operador_planta',
          'personal',
          'supervisor',
          'comprador',
          'administrativo',
          'calidad'
        ));
    END IF;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  descripcion TEXT,
  precio_kg NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  orden INT NOT NULL DEFAULT 0,
  estado VARCHAR(10) NOT NULL DEFAULT 'activo' CHECK (estado IN ('activo','inactivo')),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_categorias_codigo UNIQUE (codigo)
);

CREATE INDEX IF NOT EXISTS idx_categorias_orden ON categorias (orden);

INSERT INTO categorias (codigo, nombre, descripcion, precio_kg, orden)
VALUES
  ('exportable', 'Exportable',  'Apto para exportación',                 8.50,  1),
  ('industrial', 'Industrial',  'Para procesamiento industrial',         3.50,  2),
  ('nacional',   'Nacional',    'Para mercado nacional',                 5.00,  3),
  ('jugo',       'Jugo',        'Para extracción / molido',              2.50,  4),
  ('descarte',   'Descarte',    'No apto para comercialización',         1.00,  5),
  ('primera',    'Primera',     'Primera calidad',                       7.00,  6),
  ('segunda',    'Segunda',     'Segunda calidad',                       5.50,  7),
  ('tercera',    'Tercera',     'Tercera calidad',                       4.00,  8),
  ('cuarta',     'Cuarta',      'Cuarta calidad',                        3.00,  9),
  ('quinta',     'Quinta',      'Quinta calidad',                        2.00, 10),
  ('dedos',      'Dedos',       'Raíces pequeñas o fragmentadas',        1.50, 11)
ON CONFLICT (codigo) DO UPDATE
SET
  nombre = EXCLUDED.nombre,
  descripcion = EXCLUDED.descripcion,
  precio_kg = EXCLUDED.precio_kg,
  orden = EXCLUDED.orden;

CREATE TABLE IF NOT EXISTS lotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_lote VARCHAR(50) NOT NULL,
  productor_id BIGINT NOT NULL,
  producto VARCHAR(20) NOT NULL CHECK (producto IN ('Jengibre','Curcuma')),
  categoria_id BIGINT,
  fecha_ingreso DATE NOT NULL,
  guia_ingreso VARCHAR(50),
  peso_bruto_ingreso NUMERIC(10,2) NOT NULL,
  numero_jabas INT DEFAULT 0,
  chofer VARCHAR(100),
  placa_vehiculo VARCHAR(20),
  estado VARCHAR(20) NOT NULL DEFAULT 'sin_clasificar' CHECK (estado IN ('sin_clasificar','clasificado','asignado','liquidado','cancelado')),
  observaciones TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_lotes_productor FOREIGN KEY (productor_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_lotes_categoria FOREIGN KEY (categoria_id)
    REFERENCES categorias(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT uk_lotes_numero UNIQUE (numero_lote)
);

CREATE INDEX IF NOT EXISTS idx_lotes_estado ON lotes (estado);
CREATE INDEX IF NOT EXISTS idx_lotes_fecha ON lotes (fecha_ingreso);
CREATE INDEX IF NOT EXISTS idx_lotes_productor ON lotes (productor_id);
CREATE INDEX IF NOT EXISTS idx_lotes_categoria ON lotes (categoria_id);

CREATE TABLE IF NOT EXISTS lote_clasificacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lote_id BIGINT NOT NULL,
  categoria_id BIGINT NOT NULL,
  codigo_clasificacion VARCHAR(80),
  peso_bruto NUMERIC(10,2) NOT NULL,
  numero_jabas INT NOT NULL DEFAULT 0,
  peso_jabas NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  porcentaje_humedad NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  peso_descuento_humedad NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  peso_neto NUMERIC(10,2) NOT NULL,
  fecha_clasificacion DATE NOT NULL,
  observaciones TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_lote_clasif_lote FOREIGN KEY (lote_id)
    REFERENCES lotes(id) ON UPDATE CASCADE,
  CONSTRAINT fk_lote_clasif_categoria FOREIGN KEY (categoria_id)
    REFERENCES categorias(id) ON UPDATE CASCADE,
  CONSTRAINT uk_lote_categoria UNIQUE (lote_id, categoria_id)
);

CREATE INDEX IF NOT EXISTS idx_lote_clasif_lote ON lote_clasificacion (lote_id);
CREATE INDEX IF NOT EXISTS idx_lote_clasif_categoria ON lote_clasificacion (categoria_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_lote_clasif_codigo
  ON lote_clasificacion (codigo_clasificacion)
  WHERE codigo_clasificacion IS NOT NULL;

CREATE TABLE IF NOT EXISTS pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_pedido VARCHAR(50) NOT NULL,
  cliente_id BIGINT NOT NULL,
  producto VARCHAR(100) NOT NULL,
  categoria_id BIGINT,
  kg_solicitados NUMERIC(10,2) NOT NULL,
  precio_kg NUMERIC(10,2) NOT NULL,
  total_estimado NUMERIC(10,2) NOT NULL,
  fecha_pedido DATE NOT NULL,
  fecha_entrega DATE,
  estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','en_proceso','completado','cancelado')),
  observaciones TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_pedidos_categoria FOREIGN KEY (categoria_id)
    REFERENCES categorias(id) ON UPDATE CASCADE,
  CONSTRAINT uk_pedidos_numero UNIQUE (numero_pedido)
);

CREATE INDEX IF NOT EXISTS idx_pedidos_estado ON pedidos (estado);
CREATE INDEX IF NOT EXISTS idx_pedidos_cliente ON pedidos (cliente_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_fecha ON pedidos (fecha_pedido);

CREATE TABLE IF NOT EXISTS pedido_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  categoria_id BIGINT NOT NULL,
  kg_solicitados NUMERIC(10,2) NOT NULL,
  precio_kg NUMERIC(10,2) NOT NULL,
  kg_asignados NUMERIC(10,2) NOT NULL DEFAULT 0,
  prioridad INT NOT NULL DEFAULT 1,
  permite_sustitucion BOOLEAN NOT NULL DEFAULT FALSE,
  requiere_revision BOOLEAN NOT NULL DEFAULT FALSE,
  observaciones TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_ped_det_pedido FOREIGN KEY (pedido_id)
    REFERENCES pedidos(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_ped_det_categoria FOREIGN KEY (categoria_id)
    REFERENCES categorias(id) ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ped_det_pedido ON pedido_detalle (pedido_id);
CREATE INDEX IF NOT EXISTS idx_ped_det_categoria ON pedido_detalle (categoria_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ped_det_pedido_categoria
  ON pedido_detalle (pedido_id, categoria_id);

CREATE TABLE IF NOT EXISTS pedido_asignaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  pedido_detalle_id BIGINT,
  lote_id BIGINT NOT NULL,
  categoria_id BIGINT NOT NULL,
  codigo_division VARCHAR(80),
  sin_clasificacion_neta BOOLEAN NOT NULL DEFAULT FALSE,
  kg_asignados NUMERIC(10,2) NOT NULL,
  precio_kg NUMERIC(10,2) NOT NULL,
  subtotal NUMERIC(10,2) NOT NULL,
  fecha_asignacion DATE NOT NULL,
  observaciones TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_ped_asig_pedido FOREIGN KEY (pedido_id)
    REFERENCES pedidos(id) ON UPDATE CASCADE,
  CONSTRAINT fk_ped_asig_detalle FOREIGN KEY (pedido_detalle_id)
    REFERENCES pedido_detalle(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_ped_asig_lote FOREIGN KEY (lote_id)
    REFERENCES lotes(id) ON UPDATE CASCADE,
  CONSTRAINT fk_ped_asig_categoria FOREIGN KEY (categoria_id)
    REFERENCES categorias(id) ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ped_asig_pedido ON pedido_asignaciones (pedido_id);
CREATE INDEX IF NOT EXISTS idx_ped_asig_lote ON pedido_asignaciones (lote_id);
CREATE INDEX IF NOT EXISTS idx_ped_asig_categoria ON pedido_asignaciones (categoria_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ped_asig_codigo_division
  ON pedido_asignaciones (codigo_division)
  WHERE codigo_division IS NOT NULL;

CREATE TABLE IF NOT EXISTS kardex (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha TIMESTAMP NOT NULL DEFAULT NOW(),
  tipo_kardex VARCHAR(20) NOT NULL CHECK (tipo_kardex IN ('producto','dinero')),
  tipo_movimiento VARCHAR(20) NOT NULL CHECK (tipo_movimiento IN ('entrada','clasificacion','salida','ingreso','egreso')),
  origen VARCHAR(40) NOT NULL CHECK (origen IN ('lote_ingreso','clasificacion','asignacion_pedido','liquidacion_productor','liquidacion_cliente','adelanto','pago_directo','ajuste')),
  origen_id BIGINT,
  origen_numero VARCHAR(100),
  lote_id BIGINT,
  categoria_id BIGINT,
  peso_kg NUMERIC(12,3) DEFAULT 0.000,
  monto NUMERIC(12,2) DEFAULT 0.00,
  persona_id BIGINT,
  concepto VARCHAR(255) NOT NULL,
  observaciones TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_kardex_lote FOREIGN KEY (lote_id)
    REFERENCES lotes(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_kardex_categoria FOREIGN KEY (categoria_id)
    REFERENCES categorias(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_kardex_persona FOREIGN KEY (persona_id)
    REFERENCES personas(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_kardex_fecha ON kardex (fecha);
CREATE INDEX IF NOT EXISTS idx_kardex_tipo_kardex ON kardex (tipo_kardex);
CREATE INDEX IF NOT EXISTS idx_kardex_tipo_mov ON kardex (tipo_movimiento);
CREATE INDEX IF NOT EXISTS idx_kardex_origen ON kardex (origen, origen_id);
CREATE INDEX IF NOT EXISTS idx_kardex_lote ON kardex (lote_id);
CREATE INDEX IF NOT EXISTS idx_kardex_categoria ON kardex (categoria_id);
CREATE INDEX IF NOT EXISTS idx_kardex_persona ON kardex (persona_id);
CREATE INDEX IF NOT EXISTS idx_kardex_fecha_tipo ON kardex (fecha, tipo_kardex);

CREATE TABLE IF NOT EXISTS liquidaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_liquidacion VARCHAR(50) NOT NULL,
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('productor','cliente')),
  persona_id BIGINT NOT NULL,
  lote_id BIGINT,
  pedido_id BIGINT,
  fecha_liquidacion DATE NOT NULL,
  serie_comprobante VARCHAR(10),
  numero_comprobante VARCHAR(30),
  tipo_comprobante VARCHAR(20) DEFAULT 'ninguno' CHECK (tipo_comprobante IN ('factura','boleta','recibo','nota_credito','ninguno')),
  total_bruto NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  costo_flete NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  costo_cosecha NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  costo_maquila NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  descuento_jabas NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  otros_descuentos NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_descuentos NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_adelantos NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  total_a_pagar NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  estado VARCHAR(20) NOT NULL DEFAULT 'borrador' CHECK (estado IN ('borrador','confirmada','anulada')),
  estado_pago VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado_pago IN ('pendiente','parcial','pagado','cobrado')),
  forma_pago VARCHAR(20) CHECK (forma_pago IN ('efectivo','transferencia','cheque','mixto')),
  monto_pagado NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  fecha_pago DATE,
  observaciones TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_liq_persona FOREIGN KEY (persona_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_liq_lote FOREIGN KEY (lote_id)
    REFERENCES lotes(id) ON UPDATE CASCADE,
  CONSTRAINT fk_liq_pedido FOREIGN KEY (pedido_id)
    REFERENCES pedidos(id) ON UPDATE CASCADE,
  CONSTRAINT uk_liq_numero UNIQUE (numero_liquidacion)
);

CREATE INDEX IF NOT EXISTS idx_liq_tipo ON liquidaciones (tipo);
CREATE INDEX IF NOT EXISTS idx_liq_persona ON liquidaciones (persona_id);
CREATE INDEX IF NOT EXISTS idx_liq_estado ON liquidaciones (estado);
CREATE INDEX IF NOT EXISTS idx_liq_estado_pago ON liquidaciones (estado_pago);
CREATE INDEX IF NOT EXISTS idx_liq_fecha ON liquidaciones (fecha_liquidacion);
CREATE UNIQUE INDEX IF NOT EXISTS uq_liq_numero_comprobante
  ON liquidaciones (numero_comprobante)
  WHERE numero_comprobante IS NOT NULL;

CREATE TABLE IF NOT EXISTS liquidacion_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  liquidacion_id BIGINT NOT NULL,
  categoria_id BIGINT NOT NULL,
  peso_bruto NUMERIC(10,2) NOT NULL,
  numero_jabas INT NOT NULL DEFAULT 0,
  peso_jabas NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  porcentaje_humedad NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  peso_descuento_humedad NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  peso_neto NUMERIC(10,2) NOT NULL,
  precio_kg NUMERIC(10,2) NOT NULL,
  subtotal NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_liq_det_liquidacion FOREIGN KEY (liquidacion_id)
    REFERENCES liquidaciones(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_liq_det_categoria FOREIGN KEY (categoria_id)
    REFERENCES categorias(id) ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_liq_det_liquidacion ON liquidacion_detalle (liquidacion_id);
CREATE INDEX IF NOT EXISTS idx_liq_det_categoria ON liquidacion_detalle (categoria_id);

CREATE TABLE IF NOT EXISTS adelantos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  productor_id BIGINT NOT NULL,
  lote_id BIGINT,
  numero_comprobante VARCHAR(30),
  monto NUMERIC(10,2) NOT NULL,
  fecha DATE NOT NULL,
  motivo TEXT,
  estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente','aplicado','cancelado')),
  liquidacion_id BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_adelantos_productor FOREIGN KEY (productor_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_adelantos_lote FOREIGN KEY (lote_id)
    REFERENCES lotes(id) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_adelantos_liquidacion FOREIGN KEY (liquidacion_id)
    REFERENCES liquidaciones(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_adelantos_productor ON adelantos (productor_id);
CREATE INDEX IF NOT EXISTS idx_adelantos_estado ON adelantos (estado);
CREATE INDEX IF NOT EXISTS idx_adelantos_lote ON adelantos (lote_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_adelantos_numero_comprobante
  ON adelantos (numero_comprobante)
  WHERE numero_comprobante IS NOT NULL;

CREATE TABLE IF NOT EXISTS comprobantes_internos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('adelanto','venta','liquidacion')),
  codigo_interno VARCHAR(40) NOT NULL,
  entidad_origen VARCHAR(20) NOT NULL CHECK (entidad_origen IN ('adelantos','liquidaciones')),
  entidad_origen_id BIGINT NOT NULL,
  persona_principal_id BIGINT NOT NULL,
  productor_id BIGINT,
  cliente_id BIGINT,
  receptor_nombre VARCHAR(255),
  receptor_documento VARCHAR(30),
  receptor_rol VARCHAR(80),
  lugar_recepcion TEXT,
  gps_lat NUMERIC(10,7),
  gps_lng NUMERIC(10,7),
  gps_precision_m NUMERIC(10,2),
  fecha_evento DATE NOT NULL,
  hora_evento TIME,
  monto NUMERIC(12,2) NOT NULL DEFAULT 0,
  observaciones TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_comp_int_persona_principal FOREIGN KEY (persona_principal_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_comp_int_productor FOREIGN KEY (productor_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT fk_comp_int_cliente FOREIGN KEY (cliente_id)
    REFERENCES personas(id) ON UPDATE CASCADE,
  CONSTRAINT uk_comp_int_codigo UNIQUE (codigo_interno),
  CONSTRAINT uk_comp_int_origen_tipo UNIQUE (entidad_origen, entidad_origen_id, tipo)
);

CREATE INDEX IF NOT EXISTS idx_comp_int_tipo ON comprobantes_internos (tipo);
CREATE INDEX IF NOT EXISTS idx_comp_int_fecha ON comprobantes_internos (fecha_evento);
CREATE INDEX IF NOT EXISTS idx_comp_int_productor ON comprobantes_internos (productor_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_cliente ON comprobantes_internos (cliente_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_persona_principal ON comprobantes_internos (persona_principal_id);
CREATE INDEX IF NOT EXISTS idx_comp_int_payload_gin ON comprobantes_internos USING GIN (payload);

COMMIT;
